### ISSUE TITLE
Use with actions/cache

### ISSUE THREAD

**Issue by deemp** [nixbuild/nix-quick-install-action#33]
Hi @blaggacao, @stephank, @rickynils! Thanks a lot for your work! 

## actions/cache

Because your action makes `/nix/store` owned by an unpriviliged user, [actions/cache](https://github.com/actions/cache) can restore and save `/nix/store` without intermediate stores.

As a PoC, I made the [deemp/cache-nix-too](https://github.com/deemp/cache-nix-too) action to close https://github.com/DeterminateSystems/magic-nix-cache-action/issues/16.

`cache-nix-too` is `actions/cache`, but also caches several Nix directories as suggested by @blaggacao in https://github.com/DeterminateSystems/magic-nix-cache-action/issues/11#issuecomment-1610001962.

## README

I suggest you write in the README that `nix-quick-install-action` can be used together with `actions/cache` so that people can benefit from your action even more.

### Directoris

I'm not sure I cache the right directories in [deemp/cache-nix-too](https://github.com/deemp/cache-nix-too).
- It was suggested to exclude some of them in https://github.com/cachix/install-nix-action/issues/56#issuecomment-1059878362, but I don't know why
 - I don't know about the implications of restoring the whole `/nix/`

### Cache eviction

I can't find a good policy for cache eviction. Say, I build a docker image in each job run. Next, I cache the whole store. In the next run, I restore the whole store with that old image. If I don't remove that image, it'll be cached and restored indefinitely.

#### Possible solutions

- I tried caching only paths accessed during a run by consulting their `atime`. I used `install-nix-action`. However, I observed unstable cache sizes on `macOS` ([issue](https://github.com/deemp/cache-nix-too/issues/1)) runners.
- It may be enough to run an `installable`, `nix profile install installable`, do other steps, collect garbage, `rm -rf /nix/var/nix/profiles`, save cache, run a job again.
- Start [direnv](https://github.com/nix-community/nix-direnv) in background.
- Use [nix-heuristic-gc](https://github.com/risicle/nix-heuristic-gc)
- Somehow keep inputs (https://github.com/NixOS/nix/issues/4250, https://github.com/NixOS/nix/issues/6895)

## New action

I believe you can make a new `nix-quick-cache-action` action that caches the right directories and has a reasonable paths eviction policy.

**Comment by blaggacao** [comment]
> I don't know about the implications of restoring the whole /nix/

It may painstaikingly slow down the system on unrelated store entries that need to be compressed, transported and decompressed. Either due to cache growth or due to multiple packages / builds.

> It was suggested to exclude some of them in

Looks mostly like runtime nix data.

> it'll be cached and restored indefinitely

GH evicts about every 7 days or after ~10GB. But that's no solution to cache growth in a sprint.


Imo, the best design would be a background upload by magic cache and the cache unit would be best individual store paths.

This makes the system as efficient as it can get and using (slow) bandwidth on only the bits and pieces that are needed.

**Comment by deemp** [comment]
> Imo, the best design would be a background upload by magic cache and the cache unit would be best individual store paths.

Well, I ran into rate limit with `magic-nix-cache` on the second job run (https://github.com/DeterminateSystems/magic-nix-cache-action/issues/16).

With `nix-quick-install-action` and `cache-nix-too`, I restored a 1.5 GB `/nix` in under a minute (see [workflow](https://github.com/deemp/flakes/actions/runs/5492850567/jobs/10010629373#step:4:30)) and got a single entry for each job. I was impressed and decided to share with you.

**Comment by blaggacao** [comment]
> I ran into rate limit 

I wonder if that's something that the NixOS Foundation could touch upon in their sync-up meeting with GH engineers. :shrug: 

My bet is that this may eventually happen due to the vested interests of DetSys and their representation across the nixos governance structure.

Btw, we've been using [something similar](https://github.com/divnix/nix-cache-action) in the past.

But indeed the ~1 - 2 min penalty for cache creation & restore was critical cycle time for us.

It's not 100% related, but [here](https://github.com/divnix/std-action) we've taken an approach to _evaluate_ in a persistent "Discovery" host which brought down discovery of buildable targets from 20mins to 40s on IFD-heavy projects.
The building is then offloaded onto nixbuild from the GH worker build matrix, or alternatively the magic cache action.

**Comment by rickynils** [comment]
It looks like https://github.com/nix-community/cache-nix-action is usable with nix-quick-install. I will look into using it inside the workflows for nix-quick-install too.
