### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by deemp** [nixbuild/nix-quick-install-action#44]
@rickynils, please make a release. I need the 2.21 version

**Comment by rickynils** [comment]
@deemp Will do!

**Comment by rickynils** [comment]
@deemp New release here: [v28](https://github.com/nixbuild/nix-quick-install-action/releases/tag/v28). Unfortunately I couldn't include the very latest Nix versions, because I ran into a [MacOS issue](https://github.com/nixbuild/nix-quick-install-action/commit/2eeac83915a68b5dadc383775ef83314575801cf). But 2.21.0 is now available.

**Comment by deemp** [comment]
@rickynils, thank you! It works well
